openapi: 3.0.0
info:
  title: API Cahier de Recettes
  version: 1.0.0
  description: Documentation complète de l'API pour gérer les recettes de cuisine et les utilisateurs.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /utilisateurs/inscription:
    post:
      summary: Inscription d'un nouvel utilisateur
      tags:
        - Utilisateurs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                email:
                  type: string
                motDePasse:
                  type: string
      responses:
        '201':
          description: Utilisateur créé avec succès
        '400':
          description: Cet email est déjà utilisé ou informations invalides
  